### PR TITLE
Feature/laplace prior

### PR DESCRIPTION
**Pull request by bgoodri**
will merge as soon as merge conflicts are resolved

### CODE REVIEW

**Comment by jgabry** [comment]
@bgoodri I just updated those doc pages I mentioned in the above comments. Anything else need to be done for this PR?

**Comment by jgabry** [comment]
Do you want to also allow the lasso and laplace priors for `stan_betareg`?

**Comment by jgabry** [comment]
I just went ahead and enabled them for `stan_betareg` also.

**Comment by jgabry** [comment]
@bgoodri Is this PR ready to go? It looks ok to me, although why do you think we should include `product_normal`? Do you have a particular use case in mind for which it's important?

**Comment by bgoodri** [comment]
It is almost ready. I don't think product_normal is that good a prior, but
it is good for illustrating why it is worse than it seems.

**Pull request merged**
