### PR TITLE
hs(): Switch to regularized horseshoe

### PR DESCRIPTION
**Pull request by bgoodri**
I think this is correct, but we have to decide what to do about `hs_plus()` and what should be the arguments to `hs()`.

### CODE REVIEW

**Comment by jpiironen** [comment]
In case you're still thinking about what to do about `hs_plus`, I posted my idea in the issue thread #200 (as you probably already noticed).

**Comment by avehtari** [comment]
The paper with regularized horseshoe has been accepted to Electronic Journal of Statistics. I'm wondering what is the status of this PR?

**Comment by jgabry** [comment]
I think all the open PRs (or at least almost all of them, including this
one) will get merged before the release. But we need to get rstan out
before we do rstanarm.

**Comment by bgoodri** [comment]
@jpiironen @avehtari This may be ready to merge but it is sort of hard to test that it is correct due to all the reparameterizing. So, it would be good if you could look over the diff.

**Comment by jpiironen** [comment]
I went through the changes and didn't spot any mistakes, so I think this is good to go if you also think so!

**Pull request merged**
