### PR TITLE
Bugfix issue 49

### LINKED ISSUE #49: Wrong fixed effects estimates when running stan_glm without an intercept
I get weird fixed effects estimates when fitting a model without an intercept:

```R
library(rstanarm)
devtools::install_github("paul-buerkner/brms")
library(brms)
foo1 <- stan_glm(mpg ~ -1 + ., data=mtcars, chains=2, iter=2000, warmup=500)
foo1

foo2 <- brm(mpg ~ -1 + ., data=mtcars, chains=2, iter=2000, warmup=500)
foo2

foo3 <- glm(mpg ~ -1 + ., data = mtcars)
summary(foo3)
```
The results of `foo2` and `foo3` closely match each other while `foo1` produces very different results. Especially the  `MD_SD` (and `SD`) estimates are a bit off. This may be a result of centering the fixed effects design matrix X regardless of whether an intercept is present or not. I believe that centering is invalid in models without an intercept (at least when not corrected otherwise) but I may be mistaken.

### PR DESCRIPTION
**Pull request by jgabry**
@bgoodri I added a test for stan_glm for a model without the intercept. If the travis checks pass (everything already passes locally for me) I think this is read to merge. 

Fixes #49

### CODE REVIEW

**Comment by bgoodri** [comment]
Also remember to put an entry into NEWS.

**Comment by jgabry** [comment]
Looks like these tests are failing, although I'm not sure why. I think the failing tests are unrelated to these commits.

**Comment by bgoodri** [comment]
Yeah, I merged it anyway. In the R code, we should also prohibit models
without intercepts when the link function is insufficient to ensure that
the linear predictors are admissible. In a few places in the Stan code, we
are relying on the (existence of the) intercept to be sufficiently extreme
to impose an inequality constraint on the linear predictors.

**Comment by jgabry** [comment]
So like  link="inverse" for Gamma and link="identity" for a bunch of them? Maybe a few others too.

**Comment by bgoodri** [comment]
Yeah. And link="log" for binomial / bernoulli.

**Pull request merged**
