### PR TITLE
cleanup-betareg

### PR DESCRIPTION
**Pull request by imadmali**
Cleaned up some of the code in `continuous.stan` and updated some of the tests so that they use `algorithm = "optimizing"` instead of `algorithm = "sampling"`. (Now the runtime for `devtools:tests()` is only ~5 min.)

### CODE REVIEW

**Comment by imadmali** [comment]
closes #173

**Comment by jgabry** [comment]
@imadmali Looks good. Do all the unit tests for the functions using continuous.stan (e.g. stan_glm) still pass too?

**Comment by imadmali** [comment]
Based solely on the changes made to continuous.stan all the tests pass. But for some reason, when I use `algorithm = "optimizing"` instead of `algorithm = "sampling"` when modeling `phi` with the identity function there's a negative shape parameter error. Then the corresponding tests [here](https://github.com/stan-dev/rstanarm/blob/cleanup-betareg/tests/testthat/test_stan_betareg.R#L135-L153) fail. I'm not sure why this is happening. Examples below...

This runs:
```
N <- 200
dat <- data.frame(x = rnorm(N, 2, 1), z = rnorm(N, 2, 1))
mu <- binomial(link = "logit")$linkinv(1 + 0.2*dat$x)
phi <- dat$z - min(dat$z) + 8
dat$y <- rbeta(N, mu * phi, (1 - mu) * phi)
fit <- stan_betareg(y ~ x | z, link = "logit", link.phi = "identity",
                    prior = NULL, prior_intercept = NULL,
                    prior_z = NULL, prior_intercept_z = NULL,
                    data = dat, algorithm = "sampling", chains = 2, iter = 100)
```

But this doesn't run:
``` 
N <- 200
dat <- data.frame(x = rnorm(N, 2, 1), z = rnorm(N, 2, 1))
mu <- binomial(link = "logit")$linkinv(1 + 0.2*dat$x)
phi <- dat$z - min(dat$z) + 8
dat$y <- rbeta(N, mu * phi, (1 - mu) * phi)
fit <- stan_betareg(y ~ x | z, link = "logit", link.phi = "identity",
                    prior = NULL, prior_intercept = NULL,
                    prior_z = NULL, prior_intercept_z = NULL,
                    data = dat, algorithm = "optimizing")
```

**Comment by jgabry** [comment]
Hmm, what happens if you initialize the shape parameter to something
reasonable?

**Comment by imadmali** [comment]
I'm assuming you were referring to `phi` and yeah the following works:
```
fit <- stan_betareg(y ~ x | z, link = "logit", link.phi = "identity",
                    prior = NULL, prior_intercept = NULL,
                    prior_z = NULL, prior_intercept_z = NULL,
                    data = dat, algorithm = "optimizing",
                    seed = SEED)
```

**Comment by jgabry** [comment]
What's the difference between that and what you had before? That looks like
the same thing as in the previous comment or maybe I'm not noticing
something.

I was just saying that it might be initializing poorly if left to do random
inits and then optimization could fail. Could fail for other reasons too of
course.

**Comment by imadmali** [comment]
> What's the difference between that and what you had before? That looks like
the same thing as in the previous comment or maybe I'm not noticing
something.

Yeah it's similar but now I've fixed `phi`. Since the shape parameters enter `beta_lpdf` in a complicated way it sometimes helps to treat `phi` as a scalar (from what I remember) to generate reasonable data. I probably should play around with more edge cases since these models are really sensitive to the data.

> I was just saying that it might be initializing poorly if left to do random
inits and then optimization could fail. Could fail for other reasons too of
course.

Yeah that could've been it. Regardless, the model specification is a poor from an applied statistics point of view. I remember talking with @bgoodri about this and typically what makes sense is to only model `mu` as the linear predictor and fix `phi` as a scalar.

**Comment by jgabry** [comment]
Ok we should probably include a warning if someone tries to fit a model
that we know doesn't make sense.

Actually we probably just shouldn't allow it.

**Comment by imadmali** [comment]
As in we shouldn't allow users to fit a model with `link.phi = "identity"`?

Also, the following tests fail on the cleanup-betareg branch. I also noticed that the same tests fail on the current master branch. Are they failing for you, or am I doing something wrong when I switch branches?

```
Failed ------------------------------------------------------------------------------------------------------------------------------
1. Failure: print and summary methods ok for mcmc and vb (@test_methods.R#597) ------------------------------------------------------
print(s) does not match "Posterior sample size: 500".
Actual value: "\nModel Info:\n\n function:  stan_glmer\n family:    binomial [logit]\n formula:   cbind(incidence, size - incidence) ~ size + period + (1 | herd)\n algorithm: sampling\n priors:    see help('prior_summary')\n sample:    500 (posterior sample size)\n num obs:   56\n groups:    herd (15)\n\nEstimates:\n                                      mean   sd   2.5%   25%   50%   75%   97.5%\nsize                                 0.0    0.0  0.0    0.0   0.0   0.0   0.1   \nperiod2                             -1.0    0.3 -1.7   -1.2  -0.9  -0.7  -0.3   \nperiod3                             -1.1    0.3 -1.7   -1.3  -1.1  -0.9  -0.4   \nperiod4                             -1.5    0.5 -2.6   -1.8  -1.5  -1.2  -0.6   \nb[(Intercept) herd:1]                0.7    0.5 -0.2    0.3   0.7   0.9   1.6   \nb[(Intercept) herd:2]               -0.4    0.5 -1.3   -0.7  -0.3  -0.1   0.4   \nb[(Intercept) herd:3]                0.4    0.4 -0.4    0.2   0.4   0.7   1.1   \nb[(Intercept) herd:4]     ... <truncated>


2. Failure: recommend_QR_for_vb produces the right message (@test_misc.R#495) -------------------------------------------------------
recommend_QR_for_vb() produced no output


3. Failure: pp_validate runs for very quick example (@test_pp_validate.R#36) --------------------------------------------------------
gg <- pp_validate(fit, nreps = 2, seed = SEED) produced no output


4. Failure: predict ok for binomial (@test_predict.R#77) ----------------------------------------------------------------------------
pg$fit not equal to ps$fit.
41/51 mismatches (average diff: 0.158)
[1] -2.82 - -3.04 == 0.226
[2] -2.69 - -2.91 == 0.215
[3] -2.57 - -2.77 == 0.205
[4] -2.44 - -2.64 == 0.195
[5] -2.31 - -2.50 == 0.185
[6] -2.19 - -2.36 == 0.175
[7] -2.06 - -2.23 == 0.164
[8] -1.94 - -2.09 == 0.154
[9] -1.81 - -1.96 == 0.144
...


DONE ================================================================================================================================
```

**Comment by jgabry** [comment]
The errors from the tests for the print and summary methods are fine to
ignore. Those are my fault. I'll take care of them.

With the phi thing, I just meant that if we know optimization won't work
for a particular model we shouldn't allow it. But If we can get it to work
then great.

**Comment by jgabry** [comment]
Ok I fixed all of the failing tests you found except for the last one (predict for binomial). I don't know why that would be failing. @bgoodri any ideas?

**Comment by bgoodri** [comment]
No, but I noticed some unrelated failures when working on various branches
recently.

**Comment by imadmali** [comment]
Sorry, but I only got around to looking at this now and it looks like the latest commit that got merged was the one that used `algorithm = "optimizing"` in the tests for the `link.phi = "identity"` model. So this test will (probably) always fail: https://github.com/stan-dev/rstanarm/blob/master/tests/testthat/test_stan_betareg.R#L135-L153.

Also, @jgabry mentioned stopping users from being able to fit a model with `link.phi="identity"`, which I implemented in the latest commit of the cleanup-betareg branch.

Also, I updated the `link.phi = "sqrt"` tests to use `algorithm = "optimizing"`. The only errors that seem to come up are sampling proposal rejections (see below), which I don't think are picked up by testthat so that should be fine.

```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line -1: beta_log: Second shape parameter[6] is 0, but must be > 0!
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Rejecting initial value:
  Error evaluating the log probability at the initial value.

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line -1: beta_log: Second shape parameter[1] is 0, but must be > 0!
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Rejecting initial value:
  Error evaluating the log probability at the initial value.

...
```

**Pull request merged**
