### PR TITLE
Feature more flexible hs prior

### PR DESCRIPTION
**Pull request by bgoodri**
not quite ready to merge yet but let's make a PR

### CODE REVIEW

**Comment by bgoodri** [comment]
@jpiironen @avehtari Is this all you need for the time being?

**Comment by jpiironen** [comment]
Seems great! I realized you implemented at least the first feature that I proposed in the issue (https://github.com/stan-dev/rstanarm/issues/114), but I wasn't sure if you implemented also the second alternative (where the scale of tau depends on the unknown regression noise std sigma)? It may also be my mistake that I did not find it, but it would be useful to have that too. There is also an example Stan implementation of this prior in the appendix of our arXiv paper (https://arxiv.org/abs/1610.05559, page 11) if you want to have a look. Thanks.

**Comment by bgoodri** [comment]
I think the second thing about sigma will have to wait. We don't have an obvious way to specify options like that.

**Comment by avehtari** [comment]
Oh, that's unfortunate. Some week ago we learned from James Scott, one of the horseshoe prior paper authors, that they also would always use C+(0, sigma) instead of C+(0,1) and during the discussion he realized that there's a mistake in the paper stating  C+(0,1) instead of C+(0, sigma) used for the experiments. So it seems that the sigma should be there by default, and there is no need for an option to have it otherwise.

**Comment by bgoodri** [comment]
That would be easier.

**Comment by bgoodri** [comment]
It is straightforward to scale by sigma in Gaussian models but is that the only case where we should scale a HS (plus) prior? What about Gamma and inverse Gaussian likelihoods? What about negative binomials?

**Comment by bgoodri** [comment]
Also, would people also recommend scaling a Laplace prior in some cases but not others?

**Comment by avehtari** [comment]
It would be natural to scale with all models. In https://arxiv.org/abs/1610.05559 we have corresponding scaling for Bernoulli model and @jpiironen will write a note about scaling for other models. @jpiironen thinks that even if scaling with the scale of likelihood is added, there should be a way to provide the guess for the sparseness.

**Comment by bgoodri** [comment]
@jgabry Maybe we should always scale by the error standard deviation and then not scale up the prior standard deviations by the standard deviation of y?

**Comment by jgabry** [comment]
We're talking about the scale of the prior for tau in hs and hs_plus right?
If so then I think to always do that is fine.

Or did you means always use sigma rather than sd(y) for all glms with
adjusted prior scales?

**Comment by bgoodri** [comment]
Both, maybe

**Comment by jgabry** [comment]
For the former I think it's safe to go ahead and do that now. For the
latter, I think we'd probably want to do some comparisons first. What would
we gain from making the switch? We'd be on more theoretically solid ground,
I guess, but do you think it would improve estimates in practice?

**Comment by jpiironen** [comment]
Just to clarify, my idea was that the prior scale for tau would be b*s, where b would be given by the user and s = sqrt(-1/L_i''), where L_i'' denotes the second derivative of the ith log-likelihood term w.r.t. the linear predictor f = x*beta. For Gaussian likelihood this gives s = sigma. For other likelihoods s is generally not even a constant, but it seems reasonable plug-in values could be derived (for instance s = 2 for Bernoulli likelihood with logistic link).

At the moment I'm deriving results for some other likelihoods, but doing this for all combinations of the observation model and link function seems cumbersome and slows down adding this functionality for those cases where we know exactly what to do (e.g. Gaussian). My other concern is that for some of the cases selecting the plug-in value is not a trivial choice, and if these are hard-coded in rstanarm and later we realize a different choice might have been better, we need to either change the code or live with the earlier choice. Any thoughts on these?

**Comment by bgoodri** [comment]
I think this is ready to merge. I put the new scaling things into the `hs_plus` prior.

**Comment by bgoodri** [comment]
I spoke too soon

**Pull request merged**
