### PR TITLE
Delegate installation/configuration to rstantools

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates the `rstanarm` installation to fully delegate to `rstantools`. This will help ensure ongoing compatibility with `rstan` and its updates, and simplify some of the maintenance involved with the package.

The PR also updates the Github actions workflow to test against more combinations of R and OS versions

### CODE REVIEW

**Comment by andrjohns** [comment]
There are a lot of whitespace changes due to my IDE stripping trailing whitespace, so it might be easier to review with the whitespace changes filtered out: https://github.com/stan-dev/rstanarm/pull/574/files?diff=split&w=1

Once this merged into the master branch, I'll work with @sambrilleman on integrating with the `survival` branch so that we can get that ready for release as well

**Comment by jgabry** [comment]
Thanks @andrjohns! We've been wanting to move to using rstantools for this for a while! I don't see anything that immediately jumps out to me as problematic, but this is more in @bgoodri's wheelhouse than mine, so we should have him review this too.  @bgoodri Can you take a look at this when you have a chance? It would be great to merge this soon so that so that @andrjohns can work with @sambrilleman on getting the survival branch ready.

**Comment by jgabry** [comment]
Also @andrjohns I just added you to the r-packages team in the stan-dev organization so you can more easily contribute to whichever R package you want (thanks for all the help with the R packages!). You should be able to make branches and do maintenance stuff, etc. (not that you have to!).

**Comment by bgoodri** [comment]
I'll look at it. The rstanarm package is hard because it has to be compiled
with LTO on Windows.

**Comment by andrjohns** [comment]
@bgoodri any chance you've had time to have a look at this? It would be great to get 2.26+ compatibility in-place for `rstanarm`

**Comment by andrjohns** [comment]
@bgoodri Would you still have time to look at this? We'll need it for 2.26+

**Comment by bgoodri** [comment]
I have been looking at the ones for other packages, and since this one is similar, I am sure it will be fine. I am a little bit concerned about pending pull requests that branched off rstanarm a long time ago. I guess it could be managed but when those get merged, they might put stuff in the old locations or restore deleted files.

**Comment by andrjohns** [comment]
> I have been looking at the ones for other packages, and since this one is similar, I am sure it will be fine. I am a little bit concerned about pending pull requests that branched off rstanarm a long time ago. I guess it could be managed but when those get merged, they might put stuff in the old locations or restore deleted files.

@bgoodri if you're happy with this PR would you mind merging and putting together a new CRAN release? I'm happy to update/check the current pending PR's for any conflicts

**Comment by andrjohns** [comment]
Closing in favour of #587, will reopen once that PR is merged and I've resolved the merge conflicts with this one

**Pull request closed without merging**
