### PR TITLE
uncomment roxygen lines from cleanup[.win]

### PR DESCRIPTION
**Pull request by jgabry**
This is an alternative to #474 that adds roxygenize() to cleanup and cleanup.win instead of tracking manual pages.

### CODE REVIEW

**Comment by sambrilleman** [comment]
Yeah cool, if this works then great! I guess any solution that works for both `install_github()` and the built binaries...

**Comment by jgabry** [comment]
Yeah hopefully this works for both, but if not then we should start tracking the manual pages. 

Once we merge this we can rebuild the windows binary and also make a mac one.

**Comment by jgabry** [comment]
@bgoodri Is this no longer necessary after your commit https://github.com/stan-dev/rstanarm/commit/7b88b5c3474f87af94b8de8349457be785087dd7#diff-611496f412cac947be720d17a0ee6d7463221d14731fbc18244756271e8f5189? If it's not needed anymore let's close this. I'm trying to clean up the lots of outdated PRs lying around in the rstanarm and rstan repos.

**Comment by jgabry** [comment]
thanks!

**Pull request closed without merging**
