### PR TITLE
Dispersion to nuisance

### PR DESCRIPTION
**Pull request by jgabry**
* Renames `dispersion` to `nuisance` pretty much everywhere it's used
* Renames `overdispersion` to `reciprocal_dispersion` in output from negative binomial models. 

"nuisance" is not an ideal term but currently it's "dispersion" regardless of whether that makes sense for the given model. "nuisance"  is less misleading.

### CODE REVIEW

**Comment by jgabry** [comment]
fixed merge conflicts

**Comment by bgoodri** [comment]
Possible other names: aux{illiary}, extra, other

**Comment by jgabry** [comment]
How about we use auxiliary in text and aux in code?

**Comment by bgoodri** [comment]
Fine by me

**Comment by jgabry** [comment]
going to rename this branch now that we're using aux instead of nuisance. i'll open a new pull request

**Pull request closed without merging**
