### PR TITLE
Remove theme_set() on startup and change message

### LINKED ISSUE #257: rstanarm changes ggplot2 theme at start-up
Hi folks,

Firstly, thanks for the great package and all the hard work that's gone into it. It's really a treat to use.

`rstanarm` changes the `ggplot2` theme to `bayesplot::theme_default()` at start-up. I believe this is misguided, for two reasons:
1. It globally changes the `ggplot2` theme, even though I can say as an analyst, plots related to my model are only a subset of the plots that I am making. Obviously, this can just as easily be overriden by adding the `ggplot2` default theme to those plots, but I don't think the default of this package should  "break" the theme of other plots.
1. It's not really in the spirit of `ggplot2`'s layer-by-layer API; if you want the `bayesplot` theme, you should just add it, particularly since it's only a line of code, and otherwise leave it up to the user.

I do appreciate that `bayesplot` has a nice aesthetic, and that it's also nice to have a distinct look based on that for `rstanarm` to have, but I think this is the wrong way to go about it. I'm submitting a PR that removes the startup code and adds a quick function to set it. It also directly adds `bayesplot::theme_default()` to `plot.stanreg` and `pairs.stanreg`.

Thanks!
Malcolm

### PR DESCRIPTION
**Pull request by malcolmbarrett**
Closes #257

Reflects changes to `bayesplot` approach to themes in stan-dev/bayesplot#149

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks for this! I’ll review the bayesplot one first and once that’s merged I’ll review/merge this one for rstanarm.

**Comment by jgabry** [comment]
And don’t worry about Travis-ci errors unless they occur before it times out. But it will probably time out and error even if all is ok, so we’ll have to check it locally.

**Comment by malcolmbarrett** [comment]
I'm going to update this to match the bayesplot startup message. This one is much simpler, but anything else that needs to be done before merging?

**Comment by malcolmbarrett** [comment]
Although, now that I say it, it makes less sense for the vignettes that have raw ggplot2 to be using theme_default() without explicitly calling it in the code since rstanarm will no longer change the theme for all ggplots.

**Comment by bgoodri** [comment]
@jgabry What is up with this PR?

**Pull request merged**
