### PR TITLE
Compatibility with loo and bayesplot updates

### PR DESCRIPTION
**Pull request by jgabry**
This PR add compatibility with new functionality in the forthcoming releases of the __bayesplot__ and __loo__ packages. 

* New MCMC plots accessible via `plot.stanreg`
  - `mcmc_pairs` (also accessible via `pairs.stanreg`)
  - `mcmc_hex`

* New PPC plots accessible via `pp_check.stanreg`:
  - `ppc_bars`, `ppc_bars_grouped`, `ppc_rootogram`
  - `ppc_loo_pit`, `ppc_loo_intervals`, `ppc_loo_ribbon`

* New functions in __rstanarm__:
  - `loo_predict.stanreg`
  - `loo_linpred.stanreg`
  - `loo_predictive_interval.stanreg`
  - `loo_pit.stanreg` 

For the time being, in order to try any of the new stuff mentioned above, first run
```r
devtools::install_github("stan-dev/loo")
devtools::install_github("stan-dev/bayesplot", ref = "ppc-loo")
```
in order to get the required versions of __loo__ and __bayesplot__.

### CODE REVIEW

**Comment by avehtari** [comment]
I'll check this tomorrow...

**Comment by jgabry** [comment]
In case you want to try out what's on this branch here are the three installation commands you'll need:
 
```r
library("devtools")
install_github("stan-dev/loo")
install_github("stan-dev/bayesplot", ref = "ppc-loo")
install_github("stan-dev/rstanarm", args = "--preclean", ref = "more-loo-and-bayesplot")
```

**Comment by jgabry** [comment]
And here's example usage: 

```r
# data taken from from help("lm")
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
d <- data.frame(
  weight = c(ctl, trt), 
  group = gl(2, 10, 20, labels = c("Ctl","Trt"))
) 
print(d)

fit <- stan_glm(weight ~ group, data = d)

# using the new loo prediction functions
head(loo_predictive_interval(fit, prob = 0.8))
loo_linpred(fit, transform = TRUE) # link is identity here so doesn't do anything but just demonstrating it can be specified

# optionally, weights can be pre-computed and reused to avoid repeated computations
psis <- loo::psislw(-log_lik(fit))
loo_predictive_interval(fit, prob = 0.8, lw = psis$lw_smooth)
loo_predict(fit, type = "var", lw = psis$lw_smooth)

# graphical loo predictive checks via bayesplot
bayesplot::color_scheme_set("orange")
pp_check(fit, "loo_pit", compare = "normal")  # default compare is 'uniform'
pp_check(fit, "loo_intervals", prob = 0.5)    # default prob is 0.9

# we can also use pre-computed weights for the plots
pp_check(fit, "loo_pit", lw = psis$lw_smooth)  
```

**Comment by bgoodri** [comment]
Are these vignetted somewhere?

**Comment by jgabry** [comment]
Not yet

**Pull request merged**
