### PR TITLE
Fix CRAN NOTEs and failures

### PR DESCRIPTION
**Pull request by andrjohns**
Addresses the CRAN notes and `donttest` example failure from #586, and updates the `Makevars` files for compatibility with rstan 2.26+

### CODE REVIEW

**Comment by andrjohns** [comment]
Diff inflated due to my IDE stripping whitespace, can view with those filtered out here: https://github.com/stan-dev/rstanarm/pull/587/files?diff=unified&w=1

**Comment by jgabry** [comment]
Thanks @andrjohns!!

**Comment by andrjohns** [comment]
FYI that I've just found one more issue that will need to be resolved for 2.26+ (functions in the `functions` block modifying `target` directly), will update this PR asap

**Comment by andrjohns** [comment]
That's all the changes from me! `stanc3` doesn't like functions which directly modify `target`, as well as functions which call other `lpdf`/`lpmf` functions without having the `lpdf`/`lpmf` suffix themselves. This was causing failures with the `stan_functions` test under 2.26+. I resolved those issues and expanded the GHA workflow to test against the rstan preview as well.

I've also verified locally that everything compiles and passes under 2.31 as well, so this PR can be considered the minimal changes needed for future compatibility.

Let me know if I've missed or can clarify anything @bgoodri 

diff excluding whitespace changes: https://github.com/stan-dev/rstanarm/pull/587/files?diff=unified&w=1

**Comment by sambrilleman** [comment]
Wow epic stuff @andrjohns - thanks for keeping this thing alive!! 😅

**Review by bgoodri — APPROVED** [review]

**Pull request merged**
